version: '2'

volumes:
  postgresdata:

services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: mysecretpassword
      ports:
        - 5432:5432
      volumes:
        - postgresdata:/var/lib/postgresql/data